---
- name: Configure the initial network in the router
  gather_facts: no
  hosts: localhost
  roles:
    - router_network_01

- name: Configure the DHCP service in the router
  gather_facts: no
  hosts: localhost
  vars_prompt:
  - name: dns_mac
    prompt: "Enter the MAC address of the DNS"
    private: no

  - name: webserver_mac
    prompt: "Enter the MAC address of the webserver"
    private: no

  - name: db_mac
    prompt: "Enter the MAC address of the db"
    private: no
  roles:
    - router_dhcp

- name: Create the SSH key for Ansible
  gather_facts: no
  hosts: localhost
  roles:
    - ssh_key_creation

- name: SSH key management
  gather_facts: no
  hosts: localhost
  vars_prompt:
    - name: ssh_password
      prompt: "Introduce the password of the remote computers"
      private: yes
  roles:
    - ssh_keys_distribution

- name: Configure the DNS service in the server1
  hosts: dns_server
  roles:
    - server1_dns