---
- name: Install DNS with Ansible
  hosts: 192.168.1.10
  tasks:
    - name: Install DNS package and utilities
      dnf:
        name:
          - bind
          - bind-utils
        state: latest
