---
  - name: Verify if the SSH key for Ansible exists
    stat:
      path: /root/.ssh/ansible
    register: ssh_key

  - name: Create the SSH key for Ansible
    command: ssh-keygen -t ed25519 -f ~/.ssh/ansible -q -N ""
    when: not ssh_key.stat.exists

  - name: Warn the user that the SSH key for Ansible already exists
    debug:
      msg: "The SSH key for Ansible already exists"
    when: ssh_key.stat.exists