---
- name: Install DNS package and utilities
  dnf:
    name:
      - bind
      - bind-utils
    state: latest

- name: Configuring the main named.conf options
  copy:
    src: "{{ named_conf }}"
    dest: /etc/named.conf

- name: Create DNS zone files
  copy:
    src: "{{ zone_file }}"
    dest: "/var/named/{{ zone_file }}"

- name: Configuring the reverse zone file
  copy:
    src: "{{ reverse_zone_file }}"
    dest: "/var/named/{{ reverse_zone_file }}"

- name: Enable and restart the DNS service
  systemd:
    name: named
    enabled: yes
    state: started
    
- name: Add 'dns' service to the permanent firewall configuration
  firewalld:
    service: dns
    state: enabled
    permanent: yes
    immediate: yes